name: Publish NuGet Package to GitHub Packages

on:
  push:
    branches:
      - master
    tags:
      - 'v*'  # Runs when a tag like v1.0.0 is pushed

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup .NET SDK (9.0.x)
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      # Step 3: Add GitHub Packages NuGet Source
      - name: Add GitHub NuGet Source
        run: dotnet nuget add source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --name github --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text

      # Step 4: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Step 5: Build the project
      - name: Build project
        run: dotnet build --configuration Release --no-restore

      # Step 6: Pack the NuGet package
      - name: Pack NuGet package
        run: dotnet pack --configuration Release --no-build --output nupkgs

      # Step 7: Publish NuGet package to GitHub Packages
      - name: Publish to GitHub Packages
        run: dotnet nuget push "nupkgs/*.nupkg" --source github --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
